2021-01-20 13:16:19,693 ERROR: Exception on / [POST] [in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/rmj/github/microblog/app/routes.py", line 35, in index
    flash(_('Your post it now live!'))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask_babel/__init__.py", line 689, in gettext
    return get_domain().gettext(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask_babel/__init__.py", line 586, in gettext
    t = self.get_translations()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask_babel/__init__.py", line 554, in get_translations
    locale = get_locale()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask_babel/__init__.py", line 226, in get_locale
    rv = babel.locale_selector_func()
  File "/Users/rmj/github/microblog/app/__init__.py", line 76, in get_locale
    return request.accept_languages.best_match(app.config['LANGUAGES'])
NameError: name 'request' is not defined
2021-01-20 21:18:49,622 INFO: Microblog startup [in /Users/rmj/github/microblog/app/__init__.py:52]
2021-01-20 21:19:17,170 INFO: Microblog startup [in /Users/rmj/github/microblog/app/__init__.py:52]
2021-01-20 21:19:46,342 ERROR: Exception on /reset_password_request [POST] [in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/rmj/github/microblog/app/routes.py", line 114, in reset_password_request
    send_password_reset_email(user)
  File "/Users/rmj/github/microblog/app/email.py", line 21, in send_password_reset_email
    token = user.get_reset_password_token()
  File "/Users/rmj/github/microblog/app/models.py", line 67, in get_reset_password_token
    app.config['SECRET_KEY'], algorithm='HS256').decode('utf-8')
AttributeError: 'str' object has no attribute 'decode'
2021-01-20 21:21:06,375 INFO: Microblog startup [in /Users/rmj/github/microblog/app/__init__.py:52]
2021-01-20 21:21:18,901 ERROR: Exception on /reset_password_request [POST] [in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/rmj/github/microblog/app/routes.py", line 114, in reset_password_request
    send_password_reset_email(user)
  File "/Users/rmj/github/microblog/app/email.py", line 21, in send_password_reset_email
    token = user.get_reset_password_token()
  File "/Users/rmj/github/microblog/app/models.py", line 66, in get_reset_password_token
    {'reset_password': self.id, 'exp': time() + expires_in}, app.config['SECRET_KEY'], algorithm='HS256').decode('utf-8')
AttributeError: 'str' object has no attribute 'decode'
2021-01-20 21:22:25,097 INFO: Microblog startup [in /Users/rmj/github/microblog/app/__init__.py:52]
2021-02-01 00:15:30,483 INFO: Microblog startup [in /Users/rmj/github/microblog/app/__init__.py:52]
2021-02-01 00:18:38,773 INFO: Microblog startup [in /Users/rmj/github/microblog/app/__init__.py:52]
2021-03-10 19:17:39,978 INFO: Microblog startup [in /Users/rmj/github/microblog/app/__init__.py:52]
2021-04-12 18:51:22,246 INFO: Microblog startup [in /Users/rmj/github/microblog/app/__init__.py:52]
2021-04-12 18:59:45,594 INFO: Microblog startup [in /Users/rmj/github/microblog/app/__init__.py:52]
2021-04-12 19:02:34,183 INFO: Microblog startup [in /Users/rmj/github/microblog/app/__init__.py:52]
2021-04-12 19:02:58,006 INFO: Microblog startup [in /Users/rmj/github/microblog/app/__init__.py:52]
2021-04-12 19:03:14,296 INFO: Microblog startup [in /Users/rmj/github/microblog/app/__init__.py:52]
2021-04-12 19:07:02,126 INFO: Microblog startup [in /Users/rmj/github/microblog/app/__init__.py:52]
2021-04-12 19:07:08,571 INFO: Microblog startup [in /Users/rmj/github/microblog/app/__init__.py:52]
2021-04-12 19:08:26,116 INFO: Microblog startup [in /Users/rmj/github/microblog/app/__init__.py:52]
2021-04-12 19:10:10,849 INFO: Microblog startup [in /Users/rmj/github/microblog/app/__init__.py:52]
2021-04-12 19:11:58,937 INFO: Microblog startup [in /Users/rmj/github/microblog/app/__init__.py:52]
2021-04-12 19:12:18,553 INFO: Microblog startup [in /Users/rmj/github/microblog/app/__init__.py:52]
2021-04-12 19:21:40,281 INFO: Microblog startup [in /Users/rmj/github/microblog/app/__init__.py:52]
2021-04-12 19:25:41,418 INFO: Microblog startup [in /Users/rmj/github/microblog/app/__init__.py:52]
2021-04-12 19:31:31,402 INFO: Microblog startup [in /Users/rmj/github/microblog/app/__init__.py:52]
2021-04-12 19:32:59,541 INFO: Microblog startup [in /Users/rmj/github/microblog/app/__init__.py:52]
